# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 22:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strongpoc', '0002_contacttype_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='strongpoc.ContactType')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='strongpoc.ServiceProvider')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocs', to='strongpoc.Team')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='pointofcontact',
            unique_together=set([('team', 'service_provider', 'contact_type')]),
        ),
    ]
